# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
