# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 17:02
from __future__ import unicode_literals

from django.db import migrations
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_map', '0002_auto_20160625_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
